Repository nextcloud/android-config, pull requests merged in 2023-12, with the labels that each got.

#121 stale workflow: remove the 'needs info' label when no longer stale
  config/workflows/stale.yml
Labels: 3. to review, enhancement

#122 Update analysis.yml: Fix failing actionlint/shellcheck tests
  config/workflows/analysis.yml
Labels: 3. to review, bug

#124 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated
