Repository nextcloud/android-config, pull requests merged in 2024-07, with the labels that each got.

#185 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
  .reuse/dep5
  REUSE.toml
Labels: dependencies

#187 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#190 Bump codeQL
  .github/workflows/scorecard.yml
  config/workflows/codeql.yml
  config/workflows/scorecard.yml
Labels: 4. to release, dependencies

#192 Bump codeql to v3.25.14
  .github/workflows/scorecard.yml
  config/workflows/codeql.yml
  config/workflows/scorecard.yml
Labels: 4. to release
